//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrHeredades.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPagoProveedor
    {
        public int codPagoProveedor { get; set; }
        public Nullable<int> codProveedor { get; set; }
        public Nullable<int> codUsuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> pago { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual tbProveedor tbProveedor { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
