//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrHeredades.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPagoDeudor
    {
        public int codPagoDeudor { get; set; }
        public int codDeudor { get; set; }
        public int codUsuario { get; set; }
        public decimal pago { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual tbDeudor tbDeudor { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
