//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrHeredades.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProductoPresentacion
    {
        public int codProducto { get; set; }
        public int codPresentacion { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<short> unidades { get; set; }
        public Nullable<short> correlativo { get; set; }
    
        public virtual tbPresentacion tbPresentacion { get; set; }
        public virtual tbProducto tbProducto { get; set; }
    }
}
