//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrHeredades.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRolPermiso
    {
        public int codRol { get; set; }
        public int codPermiso { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual tbPermiso tbPermiso { get; set; }
        public virtual tbRol tbRol { get; set; }
    }
}
