//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrHeredades.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVentaProducto
    {
        public int codVenta { get; set; }
        public int codProducto { get; set; }
        public int codPresentacion { get; set; }
        public decimal cantidad { get; set; }
        public decimal precioVenta { get; set; }
    
        public virtual tbProductoPresentacion tbProductoPresentacion { get; set; }
        public virtual tbVenta tbVenta { get; set; }
    }
}
