//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrHeredades.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbVenta()
        {
            this.tbVentaProducto = new HashSet<tbVentaProducto>();
        }
    
        public int codVenta { get; set; }
        public Nullable<int> codDeudor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string numFactura { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual tbDeudor tbDeudor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbVentaProducto> tbVentaProducto { get; set; }
    }
}
