//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrHeredades.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDeudaProveedor
    {
        public int codProveedor { get; set; }
        public string proveedor { get; set; }
        public string telefono { get; set; }
        public Nullable<decimal> deuda { get; set; }
    }
}
