//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrHeredades.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vExistencias
    {
        public int codProducto { get; set; }
        public string producto { get; set; }
        public int codPresentacion { get; set; }
        public string presentacion { get; set; }
        public Nullable<decimal> existencia { get; set; }
    }
}
